version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    ports:
    - ${DB_PORT}:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=${DB_DATABASE}

  phpmyadmin:
    image: phpmyadmin
    ports:
    - 8080:80
    environment:
    - PMA_ARBITRARY=1